Document: su-exec
Title: Debian su-exec Manual
Author: <insert document author here>
Abstract: This manual describes what su-exec is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/su-exec/su-exec.sgml.gz

Format: postscript
Files: /usr/share/doc/su-exec/su-exec.ps.gz

Format: text
Files: /usr/share/doc/su-exec/su-exec.text.gz

Format: HTML
Index: /usr/share/doc/su-exec/html/index.html
Files: /usr/share/doc/su-exec/html/*.html
